@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@contentType = application/json

# POST /users
POST http://{{host}}/user/profile HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "admin@pizzetta.com",
    "password": "$2a$10$PEyMogUS81X7nzqhzo4SiOd8sauvpLuUp86kS7jsDbrDgnIXsKUi2",
}